import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  badge: {
    alignItems: 'center',
    background: 'var(--background-color-8)',
    border: '1px solid var(--text-color-3)',
    borderRadius: '16px',
    color: '#333',
    containerName: 'badge-container',
    containerType: 'normal',
    display: 'flex',
    flexGrow: 1,
    flexShrink: 1,
    fontSize: '12px',
    fontWeight: 500,
    gap: '0.5rem',
    maxHeight: '32px',
    maxWidth: 'calc(100cqw - 4rem)',
    overflow: 'hidden',
    padding: '4px 1rem',
    width: 'fit-content',
  },
  more: {
    backgroundColor: '#e0e0e0',
  },
  removeButton: {
    ':hover': {
      color: 'red',
    },
    background: 'transparent',
    border: 'none',
    color: '#666',
    cursor: 'pointer',
    fontSize: '14px',
    lineHeight: 1,
    marginLeft: '4px',
    padding: '0 4px',
  },
  value: {
    display: 'block',
    flexGrow: 1,
    flexShrink: 1,
    maxWidth: '100%',
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
});
