import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  backdrop: {
    background: 'rgba(0, 0, 0, 0.5)',
    bottom: 0,
    left: 0,
    position: 'fixed',
    right: 0,
    top: 0,
    zIndex: 10000,
  },
  button: { minWidth: '35px' },
  buttonContainer: {
    display: 'flex',
    gap: '8px',
  },
  drawer: {
    background: '#fff',
    boxShadow: '-2px 0 12px rgba(0, 0, 0, 0.15)',
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    maxWidth: '90vw',
    position: 'fixed',
    right: 0,
    top: 0,
    transition: 'transform 0.3s ease',
    width: '400px',
    zIndex: 10001,
  },
  drawerPinned: {
    background: '#fff',
    borderLeft: '1px solid #eee',
    bottom: 'unset',
    boxShadow: 'none',
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    left: 'unset',
    maxWidth: '370px',
    minWidth: '370px',
    position: 'fixed',
    right: 0,
    top: 0,
    transition: 'none',
    width: '370px',
    zIndex: 10001,
  },
  header: {
    alignItems: 'center',
    borderBottom: '1px solid #eee',
    display: 'flex',
    justifyContent: 'space-between',
    padding: '14px 16px',
  },
  title: {
    fontSize: '1.2em',
    fontWeight: 600,
  },
});
