import * as stylex from '@stylexjs/stylex';

import {
  border,
  borderRadius,
  fontSizes,
  maxWidths,
  spacing,
} from '@/styles/tokens.stylex';

export const styles = stylex.create({
  dropdownItem: {
    ':hover': {
      background: 'var(--background-color-4)',
    },
    ':last-child': { borderBottom: border.none },
    ':nth-child(even)': { background: 'var(--background-color-8)' },
    alignItems: 'center',
    background: 'none',
    borderBottom: border.xs,
    boxSizing: 'border-box',
    containerName: 'multi-select-list-row',
    containerType: 'inline-size',
    cursor: 'pointer',
    display: 'flex',
    height: spacing['3xl'],
    maxHeight: spacing['3xl'],
    maxWidth: maxWidths.fullContainerW,
    minHeight: spacing['3xl'],
    outline: spacing.none,
    transition: 'background 0.15s',
    width: maxWidths.full,
  },
  dropdownList: {
    backgroundColor: 'var(--background-color-7)',
    borderBottomLeftRadius: borderRadius.sm,
    borderBottomRightRadius: borderRadius.sm,
    boxSizing: 'border-box',
    containerName: 'multi-select-list',
    containerType: 'normal',
    display: 'flex',
    flexDirection: 'column',
    margin: spacing.none,
    maxHeight: 220,
    maxWidth: maxWidths.fullContainerW,
    overflowX: 'hidden',
    overflowY: 'auto',
    padding: spacing.none,
    width: maxWidths.full,
  },
  dropdownVirtualItem: (start: number) => ({
    left: spacing.none,
    position: 'absolute',
    top: spacing.none,
    transform: `translateY(${start}px)`,
    width: maxWidths.full,
  }),
  noResultsIcon: {
    display: 'block',
    fontSize: fontSizes.xl,
    marginBottom: spacing.sm,
  },
  noResultsItem: {
    color: 'var(--text-color-4)',
    fontSize: fontSizes.md,
    opacity: 0.7,
    padding: `${spacing['3xl']} ${spacing.none}`,
    textAlign: 'center',
    transition: 'opacity 0.3s',
    userSelect: 'none',
  },
  virtualizer: (height: number) => ({ height, position: 'relative' }),
});
