import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  container: {
    maxWidth: '100cqw',
    overflow: 'visible',
    position: 'relative',
  },
  dropdownLabel: {
    borderBottom: '1px solid #eee',
    display: 'block',
    fontWeight: 'bold',
    marginBottom: 4,
    overflow: 'hidden',
    padding: '4px 10px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdownList: {
    background: '#fff',
    border: '1px solid #ccc',
    borderRadius: 4,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.25)',
    boxSizing: 'border-box',
    maxHeight: 220,
    maxWidth: '100cqw',
    overflowX: 'hidden',
    overflowY: 'auto',
    padding: '4px 0',
    position: 'relative',
    width: '100%',
    zIndex: 9999,
  },
  dropdownOption: {
    display: 'block',
    overflow: 'hidden',
    padding: '4px 10px',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  label: {
    boxSizing: 'border-box',
    display: 'flex',
    maxWidth: '100%',
    position: 'relative',
    width: '100%',
  },
  selectedItemsDisplay: {
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    width: '100%',
  },
  triggerButton: {
    alignItems: 'center',
    background: '#fff',
    border: '1px solid #ccc',
    borderRadius: 4,
    boxSizing: 'border-box',
    cursor: 'pointer',
    display: 'flex',
    flex: '1 1 auto',

    minWidth: 0,
    overflow: 'hidden',
    padding: '6px 10px',
    textAlign: 'left',
    userSelect: 'none',
    width: '100%',
  },
});
