#!/bin/sh

# Pre-push hook for Husky v9+

echo 'Checking if we can build the app before pushing'

npm run build || {
    echo 'Build failed: View the errors above to see why.'
    exit 1;
}

echo 'Everything looks good, I am pushing this now.'
